const SITE_MAP = [
  {
    id: 'tema1',
    href: 'tema1.html',
    title: 'Тема 1. Теорія будови органічних сполук',
    lessons: [
      { href: 'urok1-1.html', title: 'Урок 1. Вуглеводні: метан, етан, етен, етин' },
      { href: 'urok1-2.html', title: 'Урок 2. Оксигеновмісні та нітрогеновмісні речовини' },
      { href: 'urok1-3.html', title: 'Урок 3. Теорія будови органічних сполук' },
      { href: 'urok1-4.html', title: 'Урок 4. Явище ізомерії та ізомери' },
      { href: 'urok1-5.html', title: "Урок 5. Карбон-карбонові зв'язки" },
      { href: 'urok1-6.html', title: 'Урок 6. Розрахункові задачі' },
      { href: 'urok1-7.html', title: 'Урок 7. Самостійна робота' },
    ]
  },
  {
    id: 'tema2',
    href: 'tema2.html',
    title: 'Тема 2. Вуглеводні',
    lessons: [
      { href: 'urok2-1.html', title: 'Урок 1. Класифікація вуглеводнів. Алкани' },
      { href: 'urok2-2.html', title: 'Урок 2. Хімічні властивості алканів' },
      { href: 'urok2-3.html', title: 'Урок 3. Алкени' },
      { href: 'urok2-4.html', title: 'Урок 4. Хімічні властивості етену' },
      { href: 'urok2-5.html', title: "Урок 5. Алкіни" },
      { href: 'urok2-6.html', title: 'Урок 6. Хімічні властивості етину' },
      { href: 'urok2-7.html', title: 'Урок 7. Арени' },
      { href: 'urok2-8.html', title: 'Урок 8. Розрахункові задачі' },
      { href: 'urok2-9.html', title: 'Урок 9. Розрахункові задачі' },
      { href: 'urok2-10.html', title: 'Урок 10. Застосування вуглеводнів' },
      { href: 'urok2-11.html', title: 'Урок 11. Розрахункові задачі' },
      { href: 'urok2-12.html', title: 'Урок 12. Контрольна робота №1' },
    ]
  },
  {
      id: 'tema3',
      href: 'tema3.html',
      title: 'Тема 3. Оксигеновмісні органічні сполуки',
      lessons: [
          { href: 'urok3-1.html', title: 'Урок 1. Спирти' },
          { href: 'urok3-2.html', title: 'Урок 2. Хімічні властивості насичених одноатомних спиртів' },
          { href: 'urok3-3.html', title: 'Урок 3. Поняття про багатоатомні спирти' },
          { href: 'urok3-4.html', title: 'Урок 4. Фенол' },
          { href: 'urok3-5.html', title: "Урок 5. Розрахункові задачі" },
          { href: 'urok3-6.html', title: 'Урок 6. Розрахункові задачі' },
          { href: 'urok3-7.html', title: 'Урок 7. Альдегіди' },
          { href: 'urok3-8.html', title: 'Урок 8. Етаналь' },
          { href: 'urok3-9.html', title: 'Урок 9. Карбонові кислоти' },
          { href: 'urok3-10.html', title: 'Урок 10. Хімічні властивості карбонових кислот' },
          { href: 'urok3-11.html', title: 'Урок 11. Естери' },
          { href: 'urok3-12.html', title: 'Урок 12. Жири' },
          { href: 'urok3-13.html', title: 'Урок 13. Вуглеводи' },
          { href: 'urok3-14.html', title: 'Урок 14. Глюкоза' },
          { href: 'urok3-15.html', title: 'Урок 15. Сахароза, крохмаль, і целюлоза' },
          { href: 'urok3-16.html', title: 'Урок 16. Практична робота №1' },
          { href: 'urok3-17.html', title: 'Урок 17. Навчальні проєкти' },
          { href: 'urok3-18.html', title: 'Урок 18. Розрахункові задачі' },
          { href: 'urok3-19.html', title: 'Урок 19. Контрольна робота №2' },
      ] },
  { id: 'tema4', href: 'tema4.html', title: 'Тема 4. Нітрогеновмісні органічні сполуки', lessons: [] },
  { id: 'tema5', href: 'tema5.html', title: 'Тема 5. Синтетичні високомолекулярні речовини', lessons: [] },
  { id: 'tema6', href: 'tema6.html', title: "Тема 6. Багатоманітність та зв'язки між класами органічних речовин", lessons: [] },
];